# SPDX-FileCopyrightText: 2024 Mustang GmbH <contact@mustang.im>>
#
# SPDX-License-Identifier: CC0-1.0

singleQuote: true
semi: false
printWidth: 100
trailingComma: none
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
