/* Generated from curl https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-core/supplemental/windowsZones.json | jq '.supplemental.windowsZones.mapTimezones | map(select(.mapZone._territory == "001")) | map({(.mapZone._type): .mapZone._other}) | add' */
export default {
  "Asia/Kabul": "Afghanistan Standard Time",
  "America/Anchorage": "Alaskan Standard Time",
  "America/Adak": "Aleutian Standard Time",
  "Asia/Barnaul": "Altai Standard Time",
  "Asia/Riyadh": "Arab Standard Time",
  "Asia/Dubai": "Arabian Standard Time",
  "Asia/Baghdad": "Arabic Standard Time",
  "America/Buenos_Aires": "Argentina Standard Time",
  "Europe/Astrakhan": "Astrakhan Standard Time",
  "America/Halifax": "Atlantic Standard Time",
  "Australia/Darwin": "AUS Central Standard Time",
  "Australia/Eucla": "Aus Central W. Standard Time",
  "Australia/Sydney": "AUS Eastern Standard Time",
  "Asia/Baku": "Azerbaijan Standard Time",
  "Atlantic/Azores": "Azores Standard Time",
  "America/Bahia": "Bahia Standard Time",
  "Asia/Dhaka": "Bangladesh Standard Time",
  "Europe/Minsk": "Belarus Standard Time",
  "Pacific/Bougainville": "Bougainville Standard Time",
  "America/Regina": "Canada Central Standard Time",
  "Atlantic/Cape_Verde": "Cape Verde Standard Time",
  "Asia/Yerevan": "Caucasus Standard Time",
  "Australia/Adelaide": "Cen. Australia Standard Time",
  "America/Guatemala": "Central America Standard Time",
  "Asia/Bishkek": "Central Asia Standard Time",
  "America/Cuiaba": "Central Brazilian Standard Time",
  "Europe/Budapest": "Central Europe Standard Time",
  "Europe/Warsaw": "Central European Standard Time",
  "Pacific/Guadalcanal": "Central Pacific Standard Time",
  "America/Chicago": "Central Standard Time",
  "America/Mexico_City": "Central Standard Time (Mexico)",
  "Pacific/Chatham": "Chatham Islands Standard Time",
  "Asia/Shanghai": "China Standard Time",
  "America/Havana": "Cuba Standard Time",
  "Etc/GMT+12": "Dateline Standard Time",
  "Africa/Nairobi": "E. Africa Standard Time",
  "Australia/Brisbane": "E. Australia Standard Time",
  "Europe/Chisinau": "E. Europe Standard Time",
  "America/Sao_Paulo": "E. South America Standard Time",
  "Pacific/Easter": "Easter Island Standard Time",
  "America/New_York": "Eastern Standard Time",
  "America/Cancun": "Eastern Standard Time (Mexico)",
  "Africa/Cairo": "Egypt Standard Time",
  "Asia/Yekaterinburg": "Ekaterinburg Standard Time",
  "Pacific/Fiji": "Fiji Standard Time",
  "Europe/Kiev": "FLE Standard Time",
  "Asia/Tbilisi": "Georgian Standard Time",
  "Europe/London": "GMT Standard Time",
  "America/Godthab": "Greenland Standard Time",
  "Atlantic/Reykjavik": "Greenwich Standard Time",
  "Europe/Bucharest": "GTB Standard Time",
  "America/Port-au-Prince": "Haiti Standard Time",
  "Pacific/Honolulu": "Hawaiian Standard Time",
  "Asia/Calcutta": "India Standard Time",
  "Asia/Tehran": "Iran Standard Time",
  "Asia/Jerusalem": "Israel Standard Time",
  "Asia/Amman": "Jordan Standard Time",
  "Europe/Kaliningrad": "Kaliningrad Standard Time",
  "Asia/Seoul": "Korea Standard Time",
  "Africa/Tripoli": "Libya Standard Time",
  "Pacific/Kiritimati": "Line Islands Standard Time",
  "Australia/Lord_Howe": "Lord Howe Standard Time",
  "Asia/Magadan": "Magadan Standard Time",
  "America/Punta_Arenas": "Magallanes Standard Time",
  "Pacific/Marquesas": "Marquesas Standard Time",
  "Indian/Mauritius": "Mauritius Standard Time",
  "Asia/Beirut": "Middle East Standard Time",
  "America/Montevideo": "Montevideo Standard Time",
  "Africa/Casablanca": "Morocco Standard Time",
  "America/Denver": "Mountain Standard Time",
  "America/Mazatlan": "Mountain Standard Time (Mexico)",
  "Asia/Rangoon": "Myanmar Standard Time",
  "Asia/Novosibirsk": "N. Central Asia Standard Time",
  "Africa/Windhoek": "Namibia Standard Time",
  "Asia/Katmandu": "Nepal Standard Time",
  "Pacific/Auckland": "New Zealand Standard Time",
  "America/St_Johns": "Newfoundland Standard Time",
  "Pacific/Norfolk": "Norfolk Standard Time",
  "Asia/Irkutsk": "North Asia East Standard Time",
  "Asia/Krasnoyarsk": "North Asia Standard Time",
  "Asia/Pyongyang": "North Korea Standard Time",
  "Asia/Omsk": "Omsk Standard Time",
  "America/Santiago": "Pacific SA Standard Time",
  "America/Los_Angeles": "Pacific Standard Time",
  "America/Tijuana": "Pacific Standard Time (Mexico)",
  "Asia/Karachi": "Pakistan Standard Time",
  "America/Asuncion": "Paraguay Standard Time",
  "Asia/Qyzylorda": "Qyzylorda Standard Time",
  "Europe/Paris": "Romance Standard Time",
  "Europe/Samara": "Russia Time Zone 3",
  "Asia/Srednekolymsk": "Russia Time Zone 10",
  "Asia/Kamchatka": "Russia Time Zone 11",
  "Europe/Moscow": "Russian Standard Time",
  "America/Cayenne": "SA Eastern Standard Time",
  "America/Bogota": "SA Pacific Standard Time",
  "America/La_Paz": "SA Western Standard Time",
  "America/Miquelon": "Saint Pierre Standard Time",
  "Asia/Sakhalin": "Sakhalin Standard Time",
  "Pacific/Apia": "Samoa Standard Time",
  "Africa/Sao_Tome": "Sao Tome Standard Time",
  "Europe/Saratov": "Saratov Standard Time",
  "Asia/Bangkok": "SE Asia Standard Time",
  "Asia/Singapore": "Singapore Standard Time",
  "Africa/Johannesburg": "South Africa Standard Time",
  "Africa/Juba": "South Sudan Standard Time",
  "Asia/Colombo": "Sri Lanka Standard Time",
  "Africa/Khartoum": "Sudan Standard Time",
  "Asia/Damascus": "Syria Standard Time",
  "Asia/Taipei": "Taipei Standard Time",
  "Australia/Hobart": "Tasmania Standard Time",
  "America/Araguaina": "Tocantins Standard Time",
  "Asia/Tokyo": "Tokyo Standard Time",
  "Asia/Tomsk": "Tomsk Standard Time",
  "Pacific/Tongatapu": "Tonga Standard Time",
  "Asia/Chita": "Transbaikal Standard Time",
  "Europe/Istanbul": "Turkey Standard Time",
  "America/Grand_Turk": "Turks And Caicos Standard Time",
  "Asia/Ulaanbaatar": "Ulaanbaatar Standard Time",
  "America/Indianapolis": "US Eastern Standard Time",
  "America/Phoenix": "US Mountain Standard Time",
  "Etc/UTC": "UTC",
  "Etc/GMT+2": "UTC-02",
  "Etc/GMT+8": "UTC-08",
  "Etc/GMT+9": "UTC-09",
  "Etc/GMT+11": "UTC-11",
  "Etc/GMT-12": "UTC+12",
  "Etc/GMT-13": "UTC+13",
  "America/Caracas": "Venezuela Standard Time",
  "Asia/Vladivostok": "Vladivostok Standard Time",
  "Europe/Volgograd": "Volgograd Standard Time",
  "Australia/Perth": "W. Australia Standard Time",
  "Africa/Lagos": "W. Central Africa Standard Time",
  "Europe/Berlin": "W. Europe Standard Time",
  "Asia/Hovd": "W. Mongolia Standard Time",
  "Asia/Tashkent": "West Asia Standard Time",
  "Asia/Hebron": "West Bank Standard Time",
  "Pacific/Port_Moresby": "West Pacific Standard Time",
  "Asia/Yakutsk": "Yakutsk Standard Time",
  "America/Whitehorse": "Yukon Standard Time"
};
