/** End-to-end media encryption for WhatsApp calls (the group-call SFU layer).
 *
 * IMPORTANT: WhatsApp does NOT use a browser's standard DTLS-SRTP / SDP / ICE
 * stack for calls — not even web.whatsapp.com. The real media plane is
 * proprietary: an SRTP master secret is generated by the call initiator,
 * Signal-encrypted to each recipient device, and delivered in the call offer
 * (SDES-style keying), feeding custom SRTP over WhatsApp's own relays. A browser
 * RTCPeerConnection cannot speak that, so the transport here is a STAND-IN, not a
 * compatible implementation (see WhatsAppCall / the review notes).
 *
 * This module is the *separate* end-to-end frame layer that group calls add on
 * top of an SFU (the same "insertable streams" idea Jitsi/Meet/Zoom use): each
 * media frame is sealed with a key derived from the Signal-shared call key. The
 * AEAD here is sound, but the exact parameters WhatsApp uses (HKDF info string,
 * which header bytes stay in the clear, the frame counter wire layout) are
 * undocumented and need a live capture. */
import { hkdfSHA256, aesGCMEncrypt, aesGCMDecrypt, concatBytes, randomBytes } from "../../Chat/WhatsApp/Crypto/primitives";

const kIvLength = 12;
const enc = (s: string) => new TextEncoder().encode(s);

/** Derives the 32-byte media frame key from the Signal-shared call key. */
export function deriveCallMediaKey(callKey: Uint8Array): Uint8Array {
  return hkdfSHA256(callKey, new Uint8Array(32), enc("WhatsApp Call E2E Media Key"), 32);
}

/** Encrypts one media frame payload. Layout: `[12-byte IV][ciphertext+GCM tag]`.
 * The IV is random per frame: both call directions derive the SAME key from the
 * shared call key, so a counter-based IV would reuse `(key, nonce)` pairs across
 * the two directions (and across separately-wired senders) — catastrophic for
 * GCM. A fresh random 96-bit IV per frame avoids that; the receiver reads it back
 * from the prefix, so no counter has to be synchronized. */
export async function encryptFrame(plaintext: Uint8Array, key: Uint8Array): Promise<Uint8Array> {
  let iv = randomBytes(kIvLength);
  return concatBytes(iv, await aesGCMEncrypt(key, iv, plaintext));
}

export async function decryptFrame(data: Uint8Array, key: Uint8Array): Promise<Uint8Array> {
  let iv = data.subarray(0, kIvLength);
  return await aesGCMDecrypt(key, iv, data.subarray(kIvLength));
}

// createEncodedStreams() may be called only once per sender/receiver.
let wired = new WeakSet<object>();

/** Wires the per-frame encrypt/decrypt onto a peer connection's senders and
 * receivers using insertable streams. Idempotent, browser-only, and feature-
 * detected; a no-op where the API is unavailable. GATED: not active in production. */
export function setupEncodedTransforms(peerConnection: RTCPeerConnection, callKey: Uint8Array): boolean {
  if (typeof (RTCRtpSender.prototype as any).createEncodedStreams != "function") {
    return false; // No insertable-streams support; E2E frame layer unavailable.
  }
  let key = deriveCallMediaKey(callKey);
  for (let sender of peerConnection.getSenders()) {
    wireEndpoint(sender, (data: Uint8Array) => encryptFrame(data, key));
  }
  for (let receiver of peerConnection.getReceivers()) {
    wireEndpoint(receiver, async (data: Uint8Array) => {
      try {
        return await decryptFrame(data, key);
      } catch (ex) {
        return null; // drop frames that fail authentication; never pass ciphertext through
      }
    });
  }
  return true;
}

/** @param process returns the transformed frame, or null to drop it. */
function wireEndpoint(endpoint: RTCRtpSender | RTCRtpReceiver, process: (data: Uint8Array) => Promise<Uint8Array | null>) {
  if (wired.has(endpoint) || !(endpoint as any).track) {
    return;
  }
  let streams = (endpoint as any).createEncodedStreams?.();
  if (!streams) {
    return;
  }
  wired.add(endpoint);
  let transform = new TransformStream({
    transform: async (frame: any, controller: any) => {
      let result = await process(new Uint8Array(frame.data));
      if (!result) {
        return; // dropped (e.g. failed authentication)
      }
      frame.data = result.buffer;
      controller.enqueue(frame);
    },
  });
  streams.readable.pipeThrough(transform).pipeTo(streams.writable);
}
