# https://github.com/crowdin/github-action/blob/master/EXAMPLES.md#upload-sources-only

name: Crowdin Upload

on:
  workflow_dispatch # manually triggered

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Upload
        uses: crowdin/github-action@v2
        with:
          config: 'app/l10n/crowdin.yml'
          upload_sources: true
          upload_translations: true
          download_translations: false
        
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}