# https://github.com/crowdin/github-action/blob/master/EXAMPLES.md#download-only-translations-without-pushing-to-a-branch

name: Crowdin Download

on:
  workflow_dispatch # manually triggered

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Download
        uses: crowdin/github-action@v2
        with:
          config: 'app/l10n/crowdin.yml'
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: translations
          create_pull_request: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}