name: Extract Strings

on:
  workflow_dispatch # manually triggered

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Extract Strings
      uses: actions/setup-node@v3
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: 18.x
#        cache: 'npm'
    - run: cd app; yarn
    - run: cd app; yarn l10n:extract
    - name: Commit & Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "Extract Strings"
        git push
