# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Installers for Linux

on:
  workflow_dispatch # manually triggered

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build installers for Linux
      uses: actions/setup-node@v3
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: 18.x
#        cache: 'npm'
    - run: cd app; npm install --legacy-peer-deps
    - run: cd lib; npm install
    - run: cd backend; npm install
    - run: cd e2; npm install --legacy-peer-deps
    - run: cd e2; npm run build:linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Installers Linux
        path: |
          e2/dist/*.deb
          e2/dist/*.rpm
          e2/dist/*.AppImage
          e2/dist/*.flatpak
          e2/dist/*.snap
