name: Parula Release for Linux

on:
  workflow_dispatch: # manually triggered
  push:
    tags: '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build release
      uses: actions/setup-node@v3
      with:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: 18.x
#        cache: 'npm'
    - run: cd app/build; sh parula-brand.sh
    - run: cd app; npm install --legacy-peer-deps
    - run: cd lib; npm install
    - run: cd backend; npm install
    - run: cd e2; npm install --legacy-peer-deps
    - run: cd e2; npm run build
    - run: cd e2; npm run build:release:linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
